<?xml version="1.0" encoding="utf-8"?><Database Name="ProjectBase" Class="LINQtoSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=&quot;(LocalDb)\Pivot Creator&quot;;Initial Catalog=ProjectBase;Integrated Security=True" SettingsObjectName="App_Project.Properties.Settings" SettingsPropertyName="ProjectBaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Brand" Member="Brand">
    <Type Name="Brand">
      <Column Name="Brand_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="brandName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bOwner_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BrandOwner_Brand" Member="BrandOwner" ThisKey="bOwner_id" OtherKey="BrandOwner_id" Type="BrandOwner" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BrandOwner" Member="BrandOwner">
    <Type Name="BrandOwner">
      <Column Name="BrandOwner_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="brandOwner" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="BrandOwner_Brand" Member="Brand" ThisKey="BrandOwner_id" OtherKey="bOwner_id" Type="Brand" />
    </Type>
  </Table>
  <Table Name="dbo.Impression" Member="Impression">
    <Type Name="Impression">
      <Column Name="impression" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="impressionType" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Industry" Member="Industry">
    <Type Name="Industry">
      <Column Name="industry" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="subIndustry" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="subIndustry2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="subIndustry3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="subIndustry4" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.db_main" Member="db_main">
    <Type Name="db_main">
      <Column Name="impression" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="xDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="impressionType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DbAll" Member="DbAll">
    <Type Name="DbAll">
      <Column Name="secondaryBrand" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="secondaryBrandOwner" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="brand" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="subIndustry" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="industry" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="brandOwner" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="subWebsite" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="website" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="publisher" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="impressions" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="inscreens" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="xDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="contentType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="adType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="product" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="xMonth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="xYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="xWeek" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ad_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Subwebsite_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Product_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecondaryBrand_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Brand_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BrandOwner_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Subindustry_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecondaryBrandOwner_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdType_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="adTypeGroup" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="isAutopromotion" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="subIndustry2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="subIndustry3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="subIndustry4" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="adURL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="adSize" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="topPublisherForCost" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="cost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="cost_gross" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="yearMonth" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="ad_idAdType_id" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="impressionType" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>