<?xml version="1.0" encoding="utf-8"?><Database Name="AdReal" Class="LINQtoSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=S1\SQL_2012R2;Initial Catalog=AdReal;Persist Security Info=True;User ID=bk" SettingsObjectName="App_Project.Properties.Settings" SettingsPropertyName="AdRealConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.dbMain_9" Member="dbMain_9s">
    <Type Name="dbMain_9">
      <Column Name="secondaryBrand" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="secondaryBrandOwner" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="brand" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="subIndustry" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="industry" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="brandOwner" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="subWebsite" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="website" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="publisher" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="impressions" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="inscreens" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="xDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="contentType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="adType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="product" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="xMonth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="xYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="xWeek" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ad_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Subwebsite_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Product_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecondaryBrand_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Brand_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BrandOwner_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Subindustry_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecondaryBrandOwner_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdType_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="adTypeGroup" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="isAutopromotion" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="subIndustry2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="subIndustry3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="subIndustry4" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="adURL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="adSize" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="topPublisherForCost" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="cost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="cost_gross" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="yearMonth" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="ad_idAdType_id" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="impressionType" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="publisherGroup" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="adTypeGroupForCost" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.db_main" Member="db_mains">
    <Type Name="db_main">
      <Column Name="xDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Ad_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Subwebsite_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Product_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecondaryBrand_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Brand_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecondaryBrandOwner_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BrandOwner_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Subindustry_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdType_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="impressions" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="inscreens" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="impressionType" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.dict_industries" Member="dict_industries">
    <Type Name="dict_industry">
      <Column Name="subIndustry_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="subIndustry4" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="subIndustry3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="subIndustry2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="subIndustry" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="industry" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.dict_brandToBrandOwner" Member="dict_brandToBrandOwners">
    <Type Name="dict_brandToBrandOwner">
      <Column Name="brandOwner" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="brand" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>